# Generated by Django 4.1.3 on 2023-04-07 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_pic', models.ImageField(blank=True, null=True, upload_to='Delivery_pics/DeliveryProfile/')),
                ('lic_pic', models.ImageField(blank=True, null=True, upload_to='Delivery_pics/DL_pic/')),
                ('address', models.CharField(max_length=100)),
                ('lic_no', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('Approve', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='Customer_pics/CustomerProfile/')),
                ('address', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_pic', models.ImageField(blank=True, null=True, upload_to='Business_pics/BusinessProfile/')),
                ('contactname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('lic_no', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('services1', models.CharField(choices=[('None', 'None'), ('Irioning', 'Irioning'), ('Dry Cleaning', 'Dry Cleaning'), ('wet Cleaning', 'wet Cleaning'), ('Shoe laundry', 'Shoe laundry'), ('Chemical Washing', 'Chemical Washing'), ('Carpet Laundry', 'Carpet Laundry')], default='None', max_length=100, null=True)),
                ('rate1', models.CharField(default=0, max_length=100, null=True)),
                ('services2', models.CharField(choices=[('None', 'None'), ('Irioning', 'Irioning'), ('Dry Cleaning', 'Dry Cleaning'), ('wet Cleaning', 'wet Cleaning'), ('Shoe laundry', 'Shoe laundry'), ('Chemical Washing', 'Chemical Washing'), ('Carpet Laundry', 'Carpet Laundry')], default='None', max_length=100, null=True)),
                ('rate2', models.CharField(default=0, max_length=100, null=True)),
                ('services3', models.CharField(choices=[('None', 'None'), ('Irioning', 'Irioning'), ('Dry Cleaning', 'Dry Cleaning'), ('wet Cleaning', 'wet Cleaning'), ('Shoe laundry', 'Shoe laundry'), ('Chemical Washing', 'Chemical Washing'), ('Carpet Laundry', 'Carpet Laundry')], default='None', max_length=100, null=True)),
                ('rate3', models.CharField(default=0, max_length=100, null=True)),
                ('services4', models.CharField(choices=[('None', 'None'), ('Irioning', 'Irioning'), ('Dry Cleaning', 'Dry Cleaning'), ('wet Cleaning', 'wet Cleaning'), ('Shoe laundry', 'Shoe laundry'), ('Chemical Washing', 'Chemical Washing'), ('Carpet Laundry', 'Carpet Laundry')], default='None', max_length=100, null=True)),
                ('rate4', models.CharField(default=0, max_length=100, null=True)),
                ('services5', models.CharField(choices=[('None', 'None'), ('Irioning', 'Irioning'), ('Dry Cleaning', 'Dry Cleaning'), ('wet Cleaning', 'wet Cleaning'), ('Shoe laundry', 'Shoe laundry'), ('Chemical Washing', 'Chemical Washing'), ('Carpet Laundry', 'Carpet Laundry')], default='None', max_length=100, null=True)),
                ('rate5', models.CharField(default=0, max_length=100, null=True)),
                ('services6', models.CharField(choices=[('None', 'None'), ('Irioning', 'Irioning'), ('Dry Cleaning', 'Dry Cleaning'), ('wet Cleaning', 'wet Cleaning'), ('Shoe laundry', 'Shoe laundry'), ('Chemical Washing', 'Chemical Washing'), ('Carpet Laundry', 'Carpet Laundry')], default='None', max_length=100, null=True)),
                ('rate6', models.CharField(default=0, max_length=100, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='B_C_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default=0, max_length=1000, null=True)),
                ('ph', models.CharField(default=0, max_length=1000, null=True)),
                ('clothingItemsname', models.CharField(default=0, max_length=1000, null=True)),
                ('clothingItems', models.CharField(default=0, max_length=1000, null=True)),
                ('clothingqty', models.CharField(default=0, max_length=1000, null=True)),
                ('rate', models.CharField(default=0, max_length=1000, null=True)),
                ('status', models.CharField(default=0, max_length=100, null=True)),
                ('userB', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_userB', to=settings.AUTH_USER_MODEL)),
                ('userC', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_userC', to=settings.AUTH_USER_MODEL)),
                ('userD', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_userD', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
